import {
  AUTHORIZED_SERVED_SCREENSHOT_CACHE_CONTROL,
  DEFAULT_KEY_PREFIX,
  DOWNLOAD_ONLY_CONTENT_TYPE,
  SERVED_SCREENSHOT_CACHE_CONTROL,
  SERVED_SCREENSHOT_CONTENT_SECURITY_POLICY,
} from "../constants/screenshots.js";
import { inertImageContentType } from "./active-content.js";
import { assertKeyPrefix, isGeneratedKey } from "./generated-key.js";
import type { ScreenshotObjectStore } from "./object-store.js";
import { safeDecodeURIComponent } from "./safe-decode-uri-component.js";

/** The screenshot a request asks for, handed to `authorize`. */
export interface ScreenshotServeRequestTarget {
  /** Generated key of the requested screenshot, already inside `keyPrefix`. */
  key: string;
}

export interface ScreenshotServeHandlerOptions {
  /**
   * Decide whether the request may read screenshots (e.g. same session check
   * as the feedback API). Defaults to public — keys are unguessable. When set,
   * responses are marked `Cache-Control: private, no-cache`: shared caches (CDN,
   * proxy) never serve an authorized screenshot to a request that skipped this
   * check, and the browser revalidates every reuse, so a revoked access takes
   * effect at once (a matching `If-None-Match` costs a `304` answered without
   * reading the object — the ETag is the never-reused key, so no backend I/O).
   * Receives the requested key for per-screenshot decisions.
   */
  authorize?: ((request: Request, target: ScreenshotServeRequestTarget) => boolean | Promise<boolean>) | undefined;
  /**
   * Namespace served: only keys `<keyPrefix><hex>.<ext>` are read, anything
   * else answers `404`. Use the `keyPrefix` given to `createScreenshotStorage`
   * (defaults to the same `beezping-`), so applications sharing a directory or
   * bucket under distinct prefixes cannot read each other's screenshots
   * through this handler.
   */
  keyPrefix?: string | undefined;
}

/**
 * `GET` handler serving screenshots from backends without their own public
 * URL (filesystem, database, memory). Mount it on the path the backend's
 * `publicBaseUrl` points at, taking the key from the last path segment:
 *
 * ```ts
 * // app/api/beezping/screenshots/[key]/route.ts
 * export const { GET } = createScreenshotServeHandler(objectStore);
 * ```
 *
 * Only keys generated by `createScreenshotStorage` under `keyPrefix` are
 * served, so the handler can neither read arbitrary paths nor another
 * namespace sharing the backend. Every response is sandboxed
 * (`Content-Security-Policy: default-src 'none'; sandbox`) and `nosniff`, and
 * only an inert image type is served inline: anything else a backend holds
 * (an SVG, `text/html`, a missing type) is sent as an
 * `application/octet-stream` attachment, so a stored object can never act as
 * a document of the application's origin.
 */
export function createScreenshotServeHandler(
  objectStore: ScreenshotObjectStore,
  { authorize, keyPrefix = DEFAULT_KEY_PREFIX }: ScreenshotServeHandlerOptions = {},
): { GET: (request: Request) => Promise<Response> } {
  assertKeyPrefix(keyPrefix, "createScreenshotServeHandler");
  const read = objectStore.get?.bind(objectStore);
  if (!read) {
    throw new Error(
      `[beezping] createScreenshotServeHandler: ${objectStore.name} has no get() — it serves screenshots from its own URLs`,
    );
  }
  const cacheControl = authorize ? AUTHORIZED_SERVED_SCREENSHOT_CACHE_CONTROL : SERVED_SCREENSHOT_CACHE_CONTROL;

  return {
    async GET(request) {
      // The namespace check is syntactic (no I/O, nothing revealed), so it runs
      // first and `authorize` only ever sees keys this handler may serve.
      const key = keyFromRequestUrl(request.url);
      if (key === null || !isGeneratedKey(key, keyPrefix)) return new Response(null, { status: 404 });
      if (authorize && !(await authorize(request, { key }))) return new Response(null, { status: 403 });
      const etag = servedScreenshotEtag(key);
      const cacheHeaders = { "Cache-Control": cacheControl, ETag: etag };
      const ifNoneMatch = parseIfNoneMatch(request.headers.get("If-None-Match"));
      // The ETag is the key, and a key names the same bytes forever: a client
      // listing it already holds this exact screenshot, so the (just
      // re-authorized) revalidation is answered without reading the object.
      if (ifNoneMatch.listedTags.includes(etag)) return new Response(null, { status: 304, headers: cacheHeaders });
      const object = await read(key);
      if (!object) return new Response(null, { status: 404 });
      // `*` only matches an existing object, so it is answered after the read.
      if (ifNoneMatch.matchesAny) return new Response(null, { status: 304, headers: cacheHeaders });
      const inertType = inertImageContentType(object.contentType);
      return new Response(object.bytes, {
        headers: {
          ...cacheHeaders,
          ...(inertType
            ? { "Content-Type": inertType }
            : { "Content-Type": DOWNLOAD_ONLY_CONTENT_TYPE, "Content-Disposition": "attachment" }),
          "Content-Security-Policy": SERVED_SCREENSHOT_CONTENT_SECURITY_POLICY,
          "X-Content-Type-Options": "nosniff",
        },
      });
    },
  };
}

/**
 * Decoded last path segment of `requestUrl`, or `null` when its percent-encoding
 * is malformed (`%`, `%ZZ`, a truncated UTF-8 sequence) — client input that is
 * simply not a key, answered like any other invalid key.
 */
function keyFromRequestUrl(requestUrl: string): string | null {
  const lastSegment = new URL(requestUrl).pathname.split("/").pop() ?? "";
  return safeDecodeURIComponent(lastSegment);
}

/**
 * Strong ETag of a served screenshot. A key is written once and never reused
 * (a new key per upload), so the key itself identifies the bytes — no hashing.
 *
 * @param key - Generated key being served.
 */
function servedScreenshotEtag(key: string): string {
  return `"${key}"`;
}

/** A parsed `If-None-Match` request header. */
interface IfNoneMatchCondition {
  /** `*` was sent: matches any existing representation. */
  matchesAny: boolean;
  /** Listed entity tags, weak prefix (`W/`) removed — `If-None-Match` uses weak comparison (RFC 9110). */
  listedTags: string[];
}

/**
 * Parse an `If-None-Match` request header: `*`, or a comma-separated list of
 * (possibly weak) entity tags.
 *
 * @param ifNoneMatch - Raw header value, `null` when absent.
 */
function parseIfNoneMatch(ifNoneMatch: string | null): IfNoneMatchCondition {
  const entries = (ifNoneMatch ?? "")
    .split(",")
    .map((entry) => entry.trim())
    .filter((entry) => entry !== "");
  return {
    matchesAny: entries.includes("*"),
    listedTags: entries.filter((entry) => entry !== "*").map((entry) => entry.replace(/^W\//, "")),
  };
}
