import { GENERATED_KEY_PATTERN, SERVED_SCREENSHOT_CACHE_CONTROL } from "../constants/screenshots.js";
import type { ScreenshotObjectStore } from "./object-store.js";

export interface ScreenshotServeHandlerOptions {
  /**
   * Decide whether the request may read screenshots (e.g. same session check
   * as the feedback API). Defaults to public — keys are unguessable.
   */
  authorize?: (request: Request) => boolean | Promise<boolean>;
}

/**
 * `GET` handler serving screenshots from backends without their own public
 * URL (filesystem, database, memory). Mount it on the path the backend's
 * `publicBaseUrl` points at, taking the key from the last path segment:
 *
 * ```ts
 * // app/api/siteping/screenshots/[key]/route.ts
 * export const { GET } = createScreenshotServeHandler(objectStore);
 * ```
 *
 * Only keys generated by `createScreenshotStorage` are served, so the handler
 * cannot be used to read arbitrary paths.
 */
export function createScreenshotServeHandler(
  objectStore: ScreenshotObjectStore,
  { authorize }: ScreenshotServeHandlerOptions = {},
): { GET: (request: Request) => Promise<Response> } {
  const read = objectStore.get?.bind(objectStore);
  if (!read) {
    throw new Error(
      `[siteping] createScreenshotServeHandler: ${objectStore.name} has no get() — it serves screenshots from its own URLs`,
    );
  }

  return {
    async GET(request) {
      if (authorize && !(await authorize(request))) return new Response(null, { status: 403 });
      const key = decodeURIComponent(new URL(request.url).pathname.split("/").pop() ?? "");
      if (!GENERATED_KEY_PATTERN.test(key)) return new Response(null, { status: 404 });
      const object = await read(key);
      if (!object) return new Response(null, { status: 404 });
      return new Response(object.bytes, {
        headers: {
          "Content-Type": object.contentType,
          "Cache-Control": SERVED_SCREENSHOT_CACHE_CONTROL,
          "X-Content-Type-Options": "nosniff",
        },
      });
    },
  };
}
